vqgan_ckpt: 

# Have to be derived from VQ-GAN Latent space dimensions
diffusion_img_size: 32
diffusion_depth_size: 32
diffusion_num_channels: 8
dim_mults: 
results_folder: checkpoints/ddpm
results_folder_postfix: ''
load_milestone: False

batch_size: 40
num_workers: 24
objective: pred_x0
save_and_sample_every: 1000
train_lr: 1e-4
timesteps: 300 # number of steps
sampling_timesteps: 250 # number of sampling timesteps (using ddim for faster inference [see citation for ddim paper])
loss_type: l1 # L1 or L2
train_num_steps: 150000 # total training steps
gradient_accumulate_every: 2 # gradient accumulation steps
ema_decay: 0.995 # exponential moving average decay
amp: False # turn on mixed precision
num_sample_rows: 1
gpus: 0

wandb_project: medicaldiffusion
wandb_entity: chavelanda
run_name: test-diffusion-001
