seed: 1234
accelerator: 'cuda'
devices: 2
gradient_accumulate_every: 1 # gradient accumulation steps
precision: 16-mixed
batch_size: 4
num_workers: 32
train_lr: 5e-5

vqvae_ckpt: ???

# Have to be derived from VQ-GAN Latent space dimensions -> normally ceil(dim/4) 
# Maybe derive automatically??
diffusion_d: ???
diffusion_h: ???
diffusion_w: ???
diffusion_num_channels: 8

dim: 32
dim_mults: 
results_folder: checkpoints/ddpm
results_folder_postfix: ''
load_milestone: 

timesteps: 300 # number of steps
loss_type: l1 # L1 or L2
train_num_steps: 100001 # total training steps
ema_decay: 0.995 # exponential moving average decay

check_val_every_n_epoch: 10

cond: True # Conditional training?
use_class_cond: True # If true, one-hot class labels are embedded and used as conditioning. If false, condition is used as it is.
null_cond_prob: 0. # Probability of using null condition

wandb_entity: ???
wandb_project: ???
run_name: ???


