batch_size: 50 # The number of samples per batch during activations calculation.
num_workers: 10 # The number of worker processes for data loading.

extractor: med3d # The specific type of ResNet model to use. ['med3d', 'vqvae', 'stunet', 'misfm']

cuda: True # A boolean indicating whether to use CUDA for computation.

# Per il nuovo metodo
epochs: 1

wandb_entity: ???
wandb_project: ???
run_name: ???

# per vqvae extractor
vqvae_checkpoint: 

# vecchio metodo
# stats_dir:  # The directory where the FID statistics will be saved. # Forse non serve nel nuovo metodo
# name: allcts-lf-07 # The name used to save the stats.