stats_dir: evaluation/fid/stats # The directory where the FID statistics will be saved.
name: dist-lrt-05 # The name used to save the stats.

batch_size: 10 # The number of samples per batch during activations calculation.
num_workers: 32 # The number of worker processes for data loading.

resnet: resnet50 # The specific type of ResNet model to use.

cuda: True # A boolean indicating whether to use CUDA for computation.