# vecchio metodo
# stats_dir:  # The directory where the FID statistics will be saved. # Forse non serve nel nuovo metodo
# name: allcts-lf-07 # The name used to save the stats.

# config in comune
batch_size: 150 # The number of samples per batch during activations calculation.
num_workers: 10 # The number of worker processes for data loading.

resnet: resnet50 # The specific type of ResNet model to use.

cuda: True # A boolean indicating whether to use CUDA for computation.

# Per il nuovo metodo
wandb_entity: 
wandb_project: 
run_name: 