stats_dir: # The directory where the FID statistics will be saved.
name: # The name used to save the stats.

batch_size: # The number of samples per batch during activations calculation.
num_workers: # The number of worker processes for data loading.

resnet: # The specific type of ResNet model to use.

cuda: # A boolean indicating whether to use CUDA for computation.