gpus: 0 # The GPU device to use for computation.
batch_size: 5 # The number of samples per batch.
data_folder: data # The data directory. Data will be saved in data_folder + run_name

# Denoiser and Gaussian diffusion parameters
vqgan_ckpt: checkpoints/vq_gan_3d/MRNet/mrnet-vqgan-01/best_val-epoch=259-step=146900.ckpt # The checkpoint file for the VQGAN model.
diffusion_img_size: 64 # The size of the images for the diffusion process.
diffusion_depth_size: 8 # The depth size for the diffusion process.
diffusion_num_channels: 8 # The number of channels in the images for the diffusion process.
dim_mults: # The dimension multipliers for the U-Net model.
timesteps: 300 # The number of timesteps for the diffusion process.

milestone: checkpoints/ddpm/MRNet/mrnet-ddpm-01/model-7.pt # The milestone file to load the model state from.

# Generation parameters
cond: True # A boolean indicating whether the model is conditioned on some input.
use_class_cond: True
class_idx: 4 # The class index for conditioning, if applicable. Leave empty for random conditioning
name_prefix: allcts-gen-07 # The prefix for the name of the output files.

n_samples: 100 # The number of samples to generate.

# Filtered generation parameters (1 for normal generation)
m: 5      # How many latents are generated to get the farthest 
train_latents: # Path to training latents


wandb_entity: chavelanda # The Weights & Biases entity (user or team) under which the project is located.
wandb_project: medicaldiffusion # The name of the Weights & Biases project.
run_name: mrnet-lf-01 # The name of the current run.
