seed: 1234
batch_size: 2
num_workers: 2

accelerator: cpu
devices: auto
accumulate_grad_batches: 1
default_root_dir: C:/Users/giach/OneDrive/Documenti/Uni/Magistrale/Tesi/medicaldiffusion/checkpoints/retrieval
default_root_dir_postfix: ''
resume: True

max_steps: 3
max_epochs: 1
precision: 32
gradient_clip_val: null
lr: 3e-4

resnet_type: resnet10
pretrain_path: 

wandb_entity: 
wandb_project: 
run_name:
