seed: 1234
batch_size: 6
num_workers: 2

accelerator: cpu
devices: auto
accumulate_grad_batches: 1
default_root_dir: C:/Users/giach/OneDrive/Documenti/Uni/Magistrale/Tesi/medicaldiffusion/checkpoints/retrieval
default_root_dir_postfix: ''
resume: False
resume_from_checkpoint:
wandb_project: medicaldiffusion
wandb_entity: chavelanda
run_name: test6
max_steps: 5
max_epochs: 1
precision: 32
gradient_clip_val: null
lr: 3e-4

embedding_dim: 256
n_codes: 2048
n_hiddens: 240

resnet_type: resnet10
pretrain_path: 


