num_workers: 32
batch_size: 20

checkpoint_path:  # Path to embedding model. If empty, calculates similarity on row data

save_path: ??? # Path to folder where to save coefficients
name: ??? # Name of the file

accelerator: cuda