seed: 1234
batch_size: 8
num_workers: 32

accelerator: cuda
devices: 1
default_root_dir: checkpoints/ss
resume: False
checkpoint_path: 

max_steps: -1
max_epochs: 16
precision: 16-mixed

lr: 3e-4
n_hiddens: 16  # Number of channels of the input in the first conv before encoding 
downsample: [4, 4, 4] 
norm_type: group
padding_type: replicate
num_groups: 16

wandb_entity: chavelanda
wandb_project: medicaldiffusion
run_name: allcts-ss-01