name: AllCTs
root_dir: data/allcts-global-128
resize_d: 1
resize_h: 1
resize_w: 1
image_channels: 1
binarize: True

metadata_name: metadata.csv
split: train

val_root_dir: data/allcts-global-128

val_metadata_name: metadata.csv
val_split: test

save_path: data/test # To be specified only when reconstructing images for vq_gan