name: AllCTs
root_dir: data/allcts-global-128
resize: 1
image_channels: 1
binarize: True
rescale: False # If True, rescale to [-1,1]. If False, stays in range [0,1]

metadata_name: metadata.csv
split: train-val
qs: # Leave empty for no filtering. Write as list. E.g. [5] or [2,3,4,5]

val_root_dir: data/allcts-gen-07

val_metadata_name: metadata.csv
val_split: all

# To be specified only when reconstructing images with autoencoder
save_path: data/test 

# To be specified for Med3D fid evaluation
d: 128
w: 128
h: 128