name: AllCTs
root_dir: data/allcts-global-128
resize_d: 1
resize_h: 1
resize_w: 1
image_channels: 1
binarize: True

metadata_name: metadata.csv
split: train-val
qs: # Leave empty for no filtering. Write as list. E.g. [5] or [2,3,4,5]

val_root_dir: data/allcts-lf-07

val_metadata_name: metadata.csv
val_split: all

save_path: data/test # To be specified only when reconstructing images for vq_gan