name: AllCTs
root_dir: data/dist-lrt-05
resize_d: 1
resize_h: 1
resize_w: 1
image_channels: 1

metadata_name: metadata.csv
split: all

val_resize_d: 1
val_resize_h: 1
val_resize_w: 1
val_image_channels: 1

val_root_dir: data/allcts-global-128
val_metadata_name: metadata.csv
val_split: test