root_dir: # The root directory where your dataset is located.

split: This could be a parameter to specify which part of the dataset to use (e.g., 'train', 'test', 'validation').

samples: 1000       # The number of pairs to sample from the dataset to generate the ms-ssim.
resize_d: 1 
resize_h: 1
resize_w: 1         # These parameters are used to resize the images in the dataset to a specific scale reduction.

image_channels: 1   # The number of channels in the images (e.g., 1 for grayscale images, 3 for RGB images).