name: MRNet
root_dir: data/mrnet
image_channels: 1

metadata_name: metadata.csv
split: train

val_root_dir: data/mrnet
val_metadata_name: metadata.csv
val_split: val

save_path: data/test # To be specified only when reconstructing images for vq_gan


