name: MRNetSS
root_dir: data/mrnet
recon_root_dir:
image_channels: 1

metadata_name: metadata.csv
recon_metadata_name: 'metadata.csv'
split: train

val_root_dir: data/mrnet
val_metadata_name: metadata.csv
val_split: val